#ifndef EP_COLLISION_H
#define EP_COLLISION_H

#include "body.h"
#include <stdbool.h>

// Axis-Aligned Bounding Box
typedef struct {
    Vec2 min;
    Vec2 max;
} AABB;

// Check if two AABBs overlap
int aabb_overlap(AABB a, AABB b);

// Combine two AABBs into one
AABB aabb_union(AABB a, AABB b);

// Compute the surface area of an AABB
float aabb_area(AABB a);

// Compute AABB for a specific body based on its shape and transform
void collision_compute_aabb(const Body* b, AABB* outAABB);

#define EP_MAX_CONTACTS 2

// Contact Manifold generated by narrow phase
typedef struct {
    Body* bodyA;
    Body* bodyB;
    int contactCount;
    Vec2 contacts[EP_MAX_CONTACTS];
    Vec2 normal; // Pointing from A to B
    float penetration;
} ContactManifold;

// Narrow phase dispatcher using GJK/EPA/Analytic tests
bool collision_narrow_phase(Body* a, Body* b, ContactManifold* m);

// Temporary immediate resolution functions (Until Step 04 SI solver)
void collision_resolve_manifold(ContactManifold* m);
void collision_resolve_world_bounds(Body* b);

#endif